### ISSUE TITLE
Where can we download Windows Setup/Installer?

### ISSUE THREAD

**Issue by mkanet** [nzbget-ng/nzbget#18] opened 2023-02-07 02:58 UTC
Sorry, I am not sure if this repository is intended to continue official development of NZBGet or not.  If it is, will your installer(s) be available eventually on:  **https://nzbget.net/download** ?  There are a lot of people on Reddit waiting to see which Repository will be the primary/preferred replacement.

Thank you so much for your effort in getting this started!

**Comment by paul-chambers** [comment] 2023-02-07 04:59
`nzbget.net` is still owned by the previous maintainer, who isn't responding to emails. So it's unlikely you'll find any updates there. The forum at that site no longer functions, either.

I'm still a) figuring out how all the different versions were built, and b) putting automation in place so they're built automatically when the version is updated. Linux releases will almost certainly be first, as that's what I'm most experienced in developing. Another developer is working on building a Windows x64 version. I hope he'll send me a pull request when he's happy with it.

At the moment I intend to use the github 'release' feature to distribute releases. I haven't yet determined if I can continue to support the existing 'self-update' mechanism with that. Even if I can, it still points at internet resources that I have no access to, so there will need to be at least one update done manually to change where nzbget looks for new releases.

Is this the 'official' continuation of nzbget development? Time will tell :)  It's gaining momentum, but I'd like to see multiple maintainers contributing before it has some legs. I know my time is limited, and it's been abandoned three times so far. I'd like more confidence in continuity than you can have when there's only a single developer at the helm.

**Comment by paul-chambers** [comment] 2023-02-07 05:02
Duplicate of issue #15

**Closed** 2023-02-07 05:01 UTC
